{% set name = "tabledata" %}
{% set version = "1.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c0ecdc547cda71d07cc5d35c68ac67753c2171f499eb3249f5223f967d44aced

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools >=38.3.0
  run:
    - dataproperty >=0.50.0,<2
    - python >=3.5
    - setuptools >=38.3.0
    - typepy >=1.1.1,<2

test:
  imports:
    - tabledata
    - tabledata._logger
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/thombashi/tabledata
  summary: tabledata is a Python library to represent tabular data. Used for pytablewriter/pytablereader/SimpleSQLite.
  dev_url: https://github.com/thombashi/tabledata
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - basnijholt
